### ISSUE TITLE
make Levenshtein implementation pluggable

### ISSUE THREAD

**Issue by mdissel** [kreeben/resin#25]
Is it planned to make the Levenshtein pluggable and for example replace it with Trigram?

**Comment by kreeben** [comment]
Oh definetly. Making the levenshtein algo implement an interface instead of being a static util method will be super-easy and since I'm acting on outside suggestions at the moment I shall have this done shortly.

**Comment by kreeben** [comment]
https://github.com/kreeben/resin/commit/4996a369c957d8415129112c855fbb54bb637116
