### ISSUE TITLE
[Questions] Architecture documentation

### ISSUE THREAD

**Issue by pherbel** [kreeben/resin#32]
Hi

Very interesting project. 

We also looking for a good search engine for Location based data (mostly addresses) and now we are working on a Elastic based version but would be great to create other prototype with this. I'm fan of .Net Core so I'm happy to see project like this implementing a good tech stuff on .Net Core. 
I have some question what came into my mind.

Are there any project or company behind this implementation or it is just your free time project?
Do you have architecture documentation? I'm very interested in how this system works, but reading the code is not the best starting point. I'm interested in a high level architecture and how the docs and trie scanned, how docs and trie held in memory or scanned on disk, etc.

Thanks

**Comment by kreeben** [comment]
Thx! Glad it caught your interest.

There is a company, [Eutektikum](http://www.eutektikum.se) (me and a co-founder), currently seeking funds. 

The documentation is in the wiki. I don't have diagrams or anything pretty describing the architecture but I am constantly working on improving all texts around Resin. 

How about a blog post around the topic of information retrieval that would describe the important parts of a search engine, such as query parsing, analyzing, tokenizing, scanning of search trees, fetching of documents, that sort of thing and relate it all to Resin's parts?

**Comment by kreeben** [comment]
https://github.com/kreeben/resin/commit/1818583c8a697dc3b4e07e5d59a7b481a698cd06
