### ISSUE TITLE
About LazyTrie Object

### ISSUE THREAD

**Issue by VictorTomaili** [kreeben/resin#4]
Hi, 
I cant build it, because i dont find any LazyTrie object or reference in solution.

**Comment by kreeben** [comment]
I Victor, sorry to hear that and sorry for not replying earlier. Lazy Trie was a mistake that I can explain if you care to hear, but more importantly, I've taken up work on this project once more and here is the latest successful build: https://github.com/kreeben/resin/commit/e35735ad01bd72fd7d1ba42ea5b35e92fdfef8e7

Thx for showing interest.

Cheers!

**Comment by kreeben** [comment]
LazyTrie does not exist any more. Check the Resin master branch for the latest stuff.
