### ISSUE TITLE
Linux version in C/C++

### ISSUE THREAD

**Issue by jobs-git** [kreeben/resin#55]

**Comment by kreeben** [comment]
You need a Linux search server, written in C/C++? What for?

**Comment by jobs-git** [comment]
so that it could be compiled w/ gcc in Linux

**Comment by kreeben** [comment]
Of course. 

Well this is written in C#.

**Comment by Immortalin** [comment]
I think a port to .NET Core is more practical. @kreeben how difficult is .NET Core compatibility?

**Comment by SebastianStehle** [comment]
Everything is written in .NET Core 2.1 already, I think.

**Comment by Immortalin** [comment]
Add a dockerfile?

**Comment by kreeben** [comment]
@Immortalin I'm not well versed in interoperability between C++ and .Net Core. But @SebastianStehle is correct in that all of Resin is written in .Net Core (currently 2.1).

**Comment by Immortalin** [comment]
I was referring to .NET Core because I thought C++ was mentioned because resin wasn't cross-platform.

**Comment by kreeben** [comment]
Resin isn't cross-platform?

**Comment by Immortalin** [comment]
Isn't .NET core more or less cross platform out of the box?

**Comment by kreeben** [comment]
@Immortalin oh definetly.
